$schema: https://json-schema.org/draft/2020-12/schema
$id: https://www.namelint.dev/namelint-config-schema.json
title: Namelint configuration file schema
description: >-
  Schema for the configuration of namelint
type: object
additionalProperties: false
properties:
  dirs:
    type: array
    description: Directories to scan
    items:
      type: string
  ignore-dirs:
    type: array
    description: Subdirectories to ignore
    items:
      type: string
  lints:
    type: array
    description: Each lint will apply a set of rules to a set of paths
    items:
      type: object
      additionalProperties: false
      properties:
        exclude-rules:
          type: array
          description: Rules to specifically disable
          items:
            type: string
        lint_id:
          type: string
        paths:
          type: array
          description: Path patterns to apply these rules to
          items:
            type: string
        rulesets:
          type: array
          description: Rules to apply specified by rule-set
          items:
            type: string
        rules:
          type: array
          description: Rules to apply specified by individually
          items:
            type: string
      anyOf:
        - required:
          - lint_id
          - rulesets
          - paths
        - required:
          - lint_id
          - rules
          - paths
  rules:
    $ref: namelint-rule-schema.json#/properties/rules
  rulesets:
    $ref: namelint-rule-schema.json#/properties/rulesets
required:
  - dirs
  - lints
